# Retail Sales Optimization - Configuration File

# AWS S3 Configuration
aws:
  region: us-east-1
  s3_bucket: retail-sales-optimization
  s3_raw_data_prefix: raw_data/
  s3_cleaned_data_prefix: cleaned_data/
  s3_transformed_data_prefix: transformed_data/
  s3_parquet_prefix: parquet_data/

# MongoDB Configuration
mongodb:
  # For AWS DocumentDB
  host: localhost  # Replace with DocumentDB endpoint
  port: 27017
  database: retail_sales_db
  
  # Collections
  collections:
    raw_sales: raw_sales
    raw_products: raw_products
    raw_calendar: raw_calendar
    cleaned_sales: cleaned_sales
    cleaned_products: cleaned_products
    cleaned_calendar: cleaned_calendar
    transformed_sales: transformed_sales
    aggregated_sales: aggregated_sales
    
  # Connection settings
  connection:
    max_pool_size: 50
    timeout_ms: 5000
    retry_writes: true
    
  # For AWS DocumentDB (uncomment when using DocumentDB)
  # tls: true
  # tls_ca_file: rds-combined-ca-bundle.pem
  # replica_set: rs0
  # read_preference: secondaryPreferred

# Local Data Configuration
local:
  dataset_path: dataset/
  raw_data_path: dataset/raw/
  cleaned_data_path: dataset/cleaned/
  transformed_data_path: dataset/transformed/

# Data Cleaning Configuration
cleaning:
  missing_value_threshold: 0.3  # Drop columns with >30% missing values
  outlier_method: iqr  # iqr or zscore
  outlier_threshold: 3
  date_formats:
    - "%Y-%m-%d"
    - "%d/%m/%Y"
    - "%m/%d/%Y"
    - "%Y/%m/%d"
  
# Feature Engineering Configuration
features:
  lag_periods: [1, 7, 14, 28]  # Days
  rolling_windows: [7, 14, 30]  # Days
  holiday_lag_days: 3
  promo_features: true
  seasonal_decomposition: true

# Model Configuration
modeling:
  train_test_split: 0.8
  validation_split: 0.1
  random_state: 42
  
  # Forecasting models
  models:
    - linear_regression
    - random_forest
    - xgboost
    - prophet
    - arima
  
  # Evaluation metrics
  metrics:
    - mse
    - rmse
    - mae
    - mape
    - r2

# Logging Configuration
logging:
  log_dir: logs/
  log_level: INFO
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Dashboard Configuration
dashboard:
  title: "Retail Sales Optimization Dashboard"
  host: localhost
  port: 8501
  theme: light

